### ISSUE TITLE
Order Tabelle

### ISSUE THREAD

**Issue by FabianGraf** [windelnde/Reporting#11]
Alle Infos zu einem Auftrag: 
Webshop, Teillieferung, Übergabe an Logistik, Versand Bestellbestätigung, Versand 10 Tage Mail, Fraud checks, Warten, Versandbestätigung, NPS Mail, wieviele Pakete, Tickets Kundenservice, Lieferzusage

**Comment by toblan** [comment]
already covered with windelnde/Data-Processes/issues/18
