### ISSUE TITLE
Scorecard windeln.it

### ISSUE THREAD

**Issue by FabianGraf** [windelnde/Reporting#12]
Analog Scorecard windeln.ch

**Comment by PhilippReindl** [comment]
10400 konnte ich matchen

Von: FabianGraf [mailto:notifications@github.com]
Gesendet: Mittwoch, 15. Juli 2015 17:16
An: windelnde/Reporting
Betreff: [Reporting] Scorecard windeln.it (#12)


Analog Scorecard windeln.ch

**Comment by nfulde** [comment]
Erledigt

**Comment by FabianGraf** [comment]
@nfulde ergänzt du bitte die Durchlaufzeiten

**Comment by nfulde** [comment]
Hab ich gemacht.
Ist die hohe Lieferdauer normal? Soll ich die Tage erhöhen?

**Comment by toblan** [comment]
ja, da es über weltpaket geht.

würde folgende cluster bilden:

1-2 Tage
3-4 Tage
5-7 Tage
mehr als 7 Tage

**Comment by FabianGraf** [comment]
Passt du es dann bitte an Nici?

Fabian Graf
Head of Business Analytics
Business Analytics

windeln.de AG
Hofmannstr. 51
D-81379 München
E-Mail:

fabian.graf@windeln.de<mailto:fabian.graf@windeln.de>


Vorstand: Alexander Brand, Konstantin Urban und Dr. Nikolaus Weinberger
Vorsitzender des Aufsichtsrates: Willi Schwerdtle

Amtsgericht München, HRB 218000


[cid:image001.png@01D0C85D.F2277410]




Von: toblan [mailto:notifications@github.com]
Gesendet: Montag, 27. Juli 2015 08:52
An: windelnde/Reporting
Cc: Fabian Graf
Betreff: Re: [Reporting] Scorecard windeln.it (#12)


ja, da es über weltpaket geht.

würde folgende cluster bilden:

1-2 Tage
3-4 Tage
5-7 Tage
mehr als 7 Tage

**Comment by nfulde** [comment]
Alles klar, ich habe es angepasst.
