### ISSUE TITLE
Artikelstammdaten tägliches Update und Entfernung Dubletten

### ISSUE THREAD

**Issue by FabianGraf** [windelnde/Reporting#15]
Artikelstammdaten pro Shop; Entfernung Dubletten; Nicht nur Published items sondern MAX(Version)

**Comment by FabianGraf** [comment]
Wir haben immer noch viele Produkte die nicht in der ItemMasterData enthalten sind, obwohl sie in PIM zu finden sind. Kann es sein, dass du immer noch den status Published als Bedingung hast? Wir müssen das unbedingt rausnehmen

**Comment by matthieu-muller** [comment]
Stimmt. Ich habe diese filter ausgenommen und laufe das update nochmal

**Comment by FabianGraf** [comment]
super, vielen Dank. Gibst du mir dann das ok bitte

Fabian Graf
Head of Business Analytics
Business Analytics

windeln.de AG
Hofmannstr. 51
D-81379 München
E-Mail:

fabian.graf@windeln.de<mailto:fabian.graf@windeln.de>


Vorstand: Alexander Brand, Konstantin Urban und Dr. Nikolaus Weinberger
Vorsitzender des Aufsichtsrates: Willi Schwerdtle

Amtsgericht München, HRB 218000


[cid:image001.png@01D0C3BE.A702B740]




Von: Matthieu Muller [mailto:notifications@github.com]
Gesendet: Dienstag, 21. Juli 2015 14:07
An: windelnde/Reporting
Cc: Fabian Graf
Betreff: Re: [Reporting] Artikelstammdaten tägliches Update und Entfernung Dubletten (#15)


Stimmt. Ich habe diese filter ausgenommen und laufe das update nochmal
