### ISSUE TITLE
Umstellung Verteiler ZAP BI 

### ISSUE THREAD

**Issue by toblan** [windelnde/Reporting#19]
Bisher haben wir eigene Verteiler für die Berichte bei 1und1 definiert.

Da jetzt aber win Verteiler senior management ('@windeln.de') und management ('@windeln.de') existieren und von der IT gepflegt werden, sollten wir auf diese umstellen.

**Comment by FabianGraf** [comment]
Senior_Management@windeln.de in Navision angelegt. Morgen in ZAP
