### ISSUE TITLE
Überarbeitung Logistik Dashboard

### ISSUE THREAD

**Issue by toblan** [windelnde/Reporting#27]
Aufträge in Fullfilment splitten nach Abendsberg / Machtlfinger
Aufträge, die auf Ware Warten bis 21 Tage unterteilen in bis 15 Tage und 16-21 Tage

**Comment by nfulde** [comment]
Erledigt.
Ich habe noch Heavy Return Deals ergänzt + einen weiteren Reiter zu detaillierten Abfrage 
"Return per Deal".
