### ISSUE TITLE
windelbar Lagerbestand

### ISSUE THREAD

**Issue by toblan** [windelnde/Reporting#3]
bei windelbar: bzw. nach „aus retouren“, „pre-buys“ (ie steht kein Kunden-Auftrag gegen) und „Rest“ (ie normales Geschäft) und jeweils Alter

**Comment by FabianGraf** [comment]
@toblan bei welchem Report soll ich das einfügen?

**Comment by FabianGraf** [comment]
@toblan Die Basis für die Lagerwert Berechnung ist die Value Entry

**Comment by toblan** [comment]
Hallo @fabian,

nicht für die Pre-Buy/Retoure/Aufträge Info (unten Mitte). Da es für WDB_AB keine Einstandpreise gibt, fehlen die Retouren…
