### ISSUE TITLE
Auswertung/Bericht zur PIM Migration

### ISSUE THREAD

**Issue by toblan** [windelnde/Reporting#30]
Hi Tobias,

diese Daten würde ich  gerne historisch sehen, um den Progress der PIM2 Migration darzustellen.

Danke,
Paul

Anfang der weitergeleiteten Nachricht:

Von: Carsten Jaensch <carsten.jaensch@windeln.de>
Betreff: Statistik PIM2.0
Datum: 28. Juli 2015 11:04:09 MESZ
An: Laura Schulte <laura.schulte@windeln.de>, Marie-Christin Kamann <mc.kamann@windeln.ch>, Maximilian Rabl <maximilian.rabl@windeln.de>, Konstantin Urban <konstantin.urban@windeln.de>
Kopie: Alexander Brand <alexander.brand@windeln.de>, Paul Hettl <paul.hettl@windeln.de>, "Peter, Dominique" <dominique.peter@windeln.de>

Guten Morgen zusammen,

hier die Statistik von heute:

Anzahl Produkte migriert					6232	
Anzahl Produkte valid					1675	
Anzahl Produkte invalid: 				3828 	(Freitag: 4501)
Anzahl group_id invalid: 					841 		(Freitag: 2011)  Hier habe ich die Regel geändert auf : group_id enthält „Marke“
Anzahl Produkte invalid ohne grouped_id: 	2987	(Freitag: 4341)

In der Kategorie Schlitten wurden gestern viele Fehler behoben, es sind noch 6 Produkte mit fehlerhaften Navisionfeldern (length_mm) vorhanden.

LG
Carsten

Hier eine Übersicht über alle Fehlerarten und ihre Anzahl

Bei dem Fehler mit der Größe schlägt folgende Regel zu
(dimensions[0] > 1200 || dimensions[1] > 600 || dimensions[2] > 600)

type	Value does not exists in list	965
base_price_unit_1	Value does not exists in list	50
base_price_unit_2	Value does not exists in list	2
brand	Value does not exists in list	54
ean	EAN is to long	3
size	Value does not exists in list	211
grouped_id	Grouped Product not equals \product_name\ or \brand + product_name\	919
class	Value does not exists in list	2
location.maximum_inventory\Direkt\	Class is not set to 'K'. Value must be grater than 0	70
location.maximum_inventorynull	Class is not set to 'K'. Value must be grater than 0	83
location.minimum_inventory\Direkt\	Class is not set to 'K'. Value must be grater than 0	70
location.minimum_inventorynull	Class is not set to 'K'. Value must be grater than 0	83
brand_nav	Value does not exists in list	2015
material	Value does not exists in list	1300
product_name	Product name has 100 or more characters	2
product_name_short_1	Name must be shorter than 30 characters	4
saison	Value does not exists in list	344
assembly_service	Value does not exists in list	3
categories	No valid category	879
retail_price	Price can not be 0	2
retail_price	Shop must contain one actual retailPrice at least.	1
supplier_article_no	Field contains spaces.	73
tags	Value does not exists in list	48
weight_gross_kg	Weight is not defined	136
height_mm	Height is not defined	25
height_mm	Total dimensions to large	93
length_mm	Length is not defined	218
length_mm	Total dimensions to large	93
weight_net_kg	Weight is not defined	283
purchase_price	Price can not be 0	39
width_mm	1040x830x760	1
width_mm	1200x800x200	8
width_mm	1400x270x165	3
width_mm	1400x600x10	2
width_mm	1400x700x5	1
width_mm	1570x250x150	10
width_mm	1600x300x200	4
width_mm	1650x140x140	4
width_mm	1700x280x150	4
width_mm	1700x360x100	3
width_mm	1750x800x300	3
width_mm	1760x310x200	3
width_mm	1800x600x10	2
width_mm	1820x250x170	7
width_mm	1850x170x170	4
width_mm	1900x280x150	1
width_mm	1900x300x300	3
width_mm	1900x350x0	1
width_mm	1900x380x170	6
width_mm	1940x350x230	1
Am 27.07.2015 um 10:43 schrieb Carsten Jaensch <carsten.jaensch@windeln.de>:

Hallo ,

hier die aktuelle Statistik von heute morgen zum Validierungszustand der Produkte in PIM2.0

Anzahl Produkte migriert					6232	
Anzahl Produkte valid					1536	
Anzahl Produkte invalid: 				3935 	(Freitag: 4501)
Anzahl group_id invalid: 					917 		(Freitag: 2011)  Hier habe ich die Regel geändert auf : group_id enthält „Marke“
Anzahl Produkte invalid ohne grouped_id: 	3097	(Freitag: 4341)

Betroffen sind die folgenden Felder

Anzahl 	Name
  "211" : "size" ,
   "1305" : "material",
   "965" : "type",
   "2013" : "brand_nav",
   "917 : "group_id",
   "874" : "shop.category_id",
   "146" : "location.article_class",
   "344" : "saison",
   "48" : "tags",
   "108" : "brand",
   "73" : "supplier_article_no",
   "415" : "location.procurement",
   "143" : "unit_of_measure.purchasePrice.currency",
   "50" : "base_price_unit_1",
   "3" : "service",
   "3" : "ean",
   "4" : "weiteres",
   "2" : "product_name",
   "3" : "shop.retailPrice.amount",
   "2" : "base_price_unit_2",
   "39" : „unit_of_measure.purchasePrice.price"

LG
Carsten

**Comment by FabianGraf** [comment]
@toblan brauchen wir das??

**Comment by toblan** [comment]
Nein, da es bald live geht...
