### ISSUE TITLE
Neuer Logistik Prozess Schweiz (In CH RepPack)

### ISSUE THREAD

**Issue by toblan** [windelnde/Reporting#31]
Regel „maximale Geschwindigkeit“
		-> To Do Tobias: Status sichtbar machen (% 2.1, % 2.2, %2.3 mit Split 2x, 3x, 4x, 5x // dazu auch Lieferzeiten)
		-> To Do Markus: in NAV umsetzen
		-> To Do Technik: in KIM & Kundenportal Status für 2.1, 2.2, 2.3 sichtbar machen

2.1) wenn komplett in Uster erfüllbar, dann komplett aus Uster an den Kunden versenden
	- next day delivery bei Bestellung vor 16 Uhr, Lieferung t+1
	- 50% Lieferungen heute, die mit den vorhandenen SKUs (??? Anzahl) voll erfüllbar sind
	- 62% Lieferungen „morgen“, und dann 1000 SKUs mehr
	- Kosten: xx (avg.) in Uster, plus 7.05 CHF CH Post
		-> To Do Markus/Christoph: Kosten Uster Lager 
			(inkl. Umlagerungen aus GB, Einlagerungen, Miete, Auslagerungen, Packen, Material) im Detail ermitteln

2.2) wenn nein, aber komplett in Berlin erfüllbar, dann komplett aus Berlin an den Kunden versenden 
	- dort packen, CH Post Label aufkleben, per LKW in die Schweiz, und dort „aufgeben“
	- idealer Prozess: cut-off 12:30, LKW holt um 17.00 ab, Einlieferung bei CH Post bis t+1 bis 18:00, Lieferung t+2
		- später: t+1 Lieferung (wie bei zalando) gegen Aufpreis ermitteln . . . 
	- 25% Lieferungen heute, die voll erfüllbar in GB sind
	- 16% Lieferungen „morgen“, wenn 1000 SKUs mehr in Uster liegen
	- Kosten: xx bei Fiege, xx für LKW Fahrt, plus 7.05 CHF CH Post
		-> To Do Markus/Christoph: Kosten Fiege, Kosten LKW Fahrt GB -> CH 

	- e-mail (zusammen mit NPS) mit Rechnung und „Einzahlschein“ versenden (geht bei Fiege nicht, da kein zweiter Druckerschacht)
		-> To Do Technik: zu programmieren

2.3) wenn nein, dann split in „max Uster, Rest GB, Rest warten“
	- Split aus Uster, GB wie bei 2.1 und 2.2
	- 25% Lieferungen heute, die gesplittet werden
	- 23% Lieferungen „morgen“, wenn 1000 SKUs mehr in Uster liegen
	- Kosten: wie oben addiert
	- im Vergleich zu heute: doppeltes Postlabel gibt es auch heute schon, aber wohl Einlagerung und Prozess in Uster für den „2.2“ Teil fällt weg
		-> To Do Markus/Christoph: welcher % Satz geht auf „warten auf Ware“
	- uU wird ein Auftrag in 4 Paketen versendet . . . wie viel sind dies wirklich?

**Comment by FabianGraf** [comment]
@ toblan verstehe nicht genau was hier gemacht werden soll

**Comment by toblan** [comment]
Kannst du schließen, da es mit Logistik Dashboard abgedeckt ist
