### ISSUE TITLE
Durchlaufzeiten

### ISSUE THREAD

**Issue by toblan** [windelnde/Reporting#4]
Durchlaufzeiten nach unserem cut-off darstellen (% Auslieferung next day wenn Auftrag < 16:00; % 2 days, 3 days, etc) - - auch nach DE / CN und Ländern getrennt - - und im Vergleich zu unserem Vesprechen

**Comment by FabianGraf** [comment]
@toblan anbei der Link zum Bericht.

http://148.251.120.20:8000/#/workbooks/2648/views

Woher kann ich die Daten für das Lieferversprechen bekommen?

**Comment by FabianGraf** [comment]
@toblan  
"Hallo Fabian, kannst du noch windeln.it in pannolini.it ändern und dort die Cluster analog der Scorecard ändern ?
Was auch super wäre, wenn wir mit mit dem Doku Sheet anfangen. Z. Bsp. welcher Cut-off gewählt ist, das Auslieferdatum führend ist etc."

Habe ich eingefügt.
