### ISSUE TITLE
Logistik Dashboard CH

### ISSUE THREAD

**Issue by toblan** [windelnde/Reporting#42]
Würde gern von dieser Basis starten:
http://148.251.120.20:8000/views/LogisticsReportv2/LogisticsDashboardv2?:embed=y&:display_count=no

und dann anstatt Retouren diese Info beifügen:

http://148.251.120.20:8000/views/DurchlaufzeitvonBestellungbisAuslieferung/AnzahlLieferungennachLagerorten?:embed=y&:display_count=no

**Comment by nfulde** [comment]
http://148.251.120.20:8000/#/views/LogisticsReportSchweiz/Windeln_chLogisticsDashboard
