### ISSUE TITLE
Wrong number of Windelbar registrations in ZAP scorecard?

### ISSUE THREAD

**Issue by tomasz-szajniuk** [windelnde/Reporting#43]
Hi,

in ZAP Windelbar Scorecard (http://windeln1.hostdich.de/Resource/Default%20Organization/Public/Scorecards/Scorecard%20Windelbar.de_agg/) there is information with number of registrations (new accounts registered at Windelbar).

I can see there following numbers:
June: 41 720
July: 56 720

<img width="530" alt="zap scorecard" src="https://cloud.githubusercontent.com/assets/13996055/9599174/da9383ae-5091-11e5-85ad-c0c400bc31bd.png">

However for following query in dvstudio I got different numbers:

SELECT COUNT(distinct w.customer_id)
FROM "magentolive.wcustomer" w
inner join "magentolive.wcustomer_eav" v
on w.customer_id=v.wcustomer_id
where cast(w.createdAt as date) between '2015-06-01' and '2015-06-30'
and v."key"='createdIn' and v."value"='WINDELBAR'

Rows: 33 848

SELECT COUNT(distinct w.customer_id)
FROM "magentolive.wcustomer" w
inner join "magentolive.wcustomer_eav" v
on w.customer_id=v.wcustomer_id
where cast(w.createdAt as date) between '2015-07-01' and '2015-07-31'
and v."key"='createdIn' and v."value"='WINDELBAR'

Rows: 58 873

*Is my query wrong, or it is something wrong with a number in ZAP?*

Cheers,
Tomasz

**Comment by FabianGraf** [comment]
@tomasz-szajniuk 

Hi, 

the problem was the date hierarchy Date Calender MW. I changed it to the normal date calender hierarchy. Now it looks fine. 

Thank you Toamsz!

**Comment by tomasz-szajniuk** [comment]
Thanks, I will test it next week.
